### ISSUE TITLE
[Feature Request] TF2 Implementation

### ISSUE THREAD

**Issue by SauravMaheshkar** [ZimpleX/gcn-ipdps19#1]
Can the authors please provide a TF2 implementation of the paper. TF2 is better suited for multi-GPU / TPU training environments and overall provides a much simpler API.

PS: I'd love to help out with this.

**Comment by ZimpleX** [comment]
Hi Saurav,

Thanks for your interest and sorry for the late reply. 

I agree that TF2 would be valuable to the community. While I am very interested in this, I currently don't have the bandwidth to do this additional implementation. 

It's great that you would love to help out with this. I appreciate your support and would love to know about your thoughts! If you want to further discuss this, you can contact us by email: Hanqing Zeng (zengh@usc.edu) and Hongkuan Zhou (hongkuaz@usc.edu). 

PS: This repo is kind of out-dated. Maybe we can discuss adding TF2 support to [GraphSAINT](https://github.com/GraphSAINT/GraphSAINT) (where a [sub-directory](https://github.com/GraphSAINT/GraphSAINT/tree/master/ipdps19_cpp) contains optimized version of this IPDPS work). 

Thanks
